version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    open-pull-requests-limit: 3
    schedule: # temporary schedule while evaluating this
      interval: "weekly" 
      day: "monday"
      time: "10:00"
      timezone: "US/Pacific"
    reviewers:
      - "tdyas"
      - "asherf"

