name: CI

# Trigger this workflow on any push (to main) or pull request.
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    name: Build and test

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '^1.14.9'
      - run: scripts/ci.sh
      - name: Build smoketest docker image
        uses: docker/build-push-action@v3
        with:
          tags: smoketest:ci
          build-args: APP_NAME=smoketest
      - name: Build casload docker image
        uses: docker/build-push-action@v3
        with:
          tags: casload:ci
          build-args: APP_NAME=casload
