name: CI

# Trigger this workflow on any push (to main) or pull request.
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    name: Build and test

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.17.8'
      - name: Cache pants
        uses: actions/cache@v2
        with:
          key: ${{ runner.os }}-${{ hashFiles('pants*toml') }}-v2
          path: |
             ~/.cache/pants/setup
      - name: Set env vars
        run: |
          echo 'PANTS_CONFIG_FILES=+["${{ github.workspace }}/pants.ci.toml"]' >> ${GITHUB_ENV}
          echo 'TOOLCHAIN_AUTH_TOKEN=${{ secrets.TOOLCHAIN_AUTH_TOKEN }}' >> ${GITHUB_ENV}
      - name: Pants Bootstrap
        run: ./pants version
      - name: Lint & check
        run: |
          ./pants lint check ::
      - name: Tests
        run: |
          ./pants test ::
      - name: Build smoketest docker image
        uses: docker/build-push-action@v2
        with:
          tags: smoketest:ci
          build-args: APP_NAME=smoketest
      - name: Build casload docker image
        uses: docker/build-push-action@v2
        with:
          tags: casload:ci
          build-args: APP_NAME=casload
