name: Publish to DockerHub
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build & Publish nightly smoketest
      uses: docker/build-push-action@v2
      with:
        build-args: APP_NAME=smoketest
        name: toolchainlabs/remote-api-tools-smoketest:nighly
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_ACCESS_TOKEN }}
        tag_semver: true