name: Publish to DockerHub
on:
  push:
    branches:
      - main
jobs:
  publish-dockerhub:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_ACCESS_TOKEN }}
    - name: Build & Publish nightly smoketest
      id: docker_build_smoketest
      uses: docker/build-push-action@v5
      with:
        build-args: APP_NAME=smoketest
        tags: toolchainlabs/remote-api-tools-smoketest:nightly
        push: true
    - name: smoketest image digest
      run: echo ${{ steps.docker_build_smoketest.outputs.digest }}
    - name: Build & Publish nightly casload
      id: docker_build_casload
      uses: docker/build-push-action@v5
      with:
        build-args: APP_NAME=casload
        tags: toolchainlabs/remote-api-tools-casload:nightly
        push: true
    - name: casload image digest
      run: echo ${{ steps.docker_build_casload.outputs.digest }}