name: Publish to DockerHub
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_ACCESS_TOKEN }}
    - name: Build & Publish nightly smoketest
      id: docker_build_smoketest
      uses: docker/build-push-action@v2
      with:
        build-args: APP_NAME=smoketest
        name: toolchainlabs/remote-api-tools-smoketest:nighly
        tag_semver: true
        push: true
    - name: Image digest
      run: echo ${{ steps.docker_build_smoketest.outputs.digest }}